tasks:
  - name: Install dependencies, start local Arweave gateway
    init: sleep 1 && yarn
    command: npx arlocal --y
  - name: Start server
    command: |
      export CLIENT_URL="$(gp url 1984)"
      gp await-port 1984
      npm start
ports:
  - port: 3000
    visibility: public
  - port: 1984
    visibility: public