tasks:
  - name: Install dependencies, start local Arweave gateway
    init: yarn
    command: npx arlocal --y
  - name: Start server
    command: |
      export CLIENT_URL="$(gp url 35729)/livereload.js?snipver=1&port=443"
      gp await-port 1984
      npm start
ports:
  - port: 3000
    visibility: public
  - port: 1984
    visibility: public